# Copyright (c) 2023 Cisco Systems, Inc. and its affiliates All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
  labels:
    app: loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan
          image: docker.io/waris95/martian-bank-loan
          envFrom:
            - configMapRef:
                name: configmap-martianbank
          env:
            - name: SERVICE_PROTOCOL
              value: {{.Values.SERVICE_PROTOCOL}}

---
apiVersion: v1
kind: Service
metadata:
    name: loan
spec:
    selector:
        app: loan
    ports:
        - protocol: TCP
          port: 50053
          targetPort: 50053