# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import account_details_pb2 as account__details__pb2


class AccountDetailsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccountDetails = channel.unary_unary(
                '/AccountDetailsService/GetAccountDetails',
                request_serializer=account__details__pb2.GetAccountDetailsRequest.SerializeToString,
                response_deserializer=account__details__pb2.GetAccountDetailsResponse.FromString,
                )


class AccountDetailsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAccountDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountDetailsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccountDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountDetails,
                    request_deserializer=account__details__pb2.GetAccountDetailsRequest.FromString,
                    response_serializer=account__details__pb2.GetAccountDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AccountDetailsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountDetailsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAccountDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AccountDetailsService/GetAccountDetails',
            account__details__pb2.GetAccountDetailsRequest.SerializeToString,
            account__details__pb2.GetAccountDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
