apiVersion: v1 
kind: Service 
metadata:  
  name: lb-apiclarity 
  labels: 
    app: apiclarity-apiclarity 
spec: 
  selector: 
    app: apiclarity-apiclarity 
  type: LoadBalancer 
  ports:  
  - name: http 
    port: 8080 
    targetPort: 8080 
    protocol: TCP 
